### ISSUE TITLE
这个怎么用

### ISSUE THREAD

**Issue by cx4** [one-pupil/study#25]
大佬，微信H5 分享缩略图的配置这个怎么用啊

**Comment by imondo** [comment]
可以看下我以前写的


https://juejin.cn/post/6844904150241640461


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: cx4 ***@***.***&gt;
发送时间: 2021年7月8日 20:25
收件人: imondo/study ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[imondo/study] 这个怎么用 (#25)





 
大佬，微信H5 分享缩略图的配置这个怎么用啊
